Load Channels with `.` in their name
angelolab/alpineer pull request #38
Opened 2023-10-11 00:00 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Allows loading of channels with a period in their name (other than for the file extension)

**How did you implement your changes**

Used `os.path.splitext` instead of `.split` for the path.

**Remaining issues**

N/A.

2023-10-12 19:31 UTC, srivarra commented
@camisowers Yeah I'll add a test. `load_imgs_from_dir` does not have this issue. It uses `io_utils.remove_file_extensions` to remove file extensions, instead of directly splitting the string itself.

2023-10-13 18:38 UTC, camisowers requested changes
Looks good! Just one minor fix.

2023-10-13 18:38 UTC, camisowers commented on src/alpineer/load_utils.py
> +        # channels_no_delim = [os.path.splitext(img)[0] for img in channels]
This line should be deleted.

2023-10-13 18:54 UTC, camisowers approved these changes

2023-10-13 19:54 UTC, alex-l-kong approved these changes
Good stuff

2023-10-13 19:58 UTC, merged